### ISSUE TITLE
Could not find function "ReadH5MU"

### ISSUE THREAD

**Issue by gjhuizing** [PMBio/muon.r#3]
Hi,

I'm trying to load a Muon .h5mu file in R as a Seurat object. I installed the package but the reading function is not found.

```
> ReadH5MU("test.mu", "seurat")
Error in ReadH5MU("test.mu", "seurat") : 
  could not find function "ReadH5MU"
```
Replicated on an Ubuntu machine and on a Mac.

Best

Geert-Jan

**Comment by gtca** [comment]
Dear @gjhuizing,

Thanks for reaching out. We have been working on a better version of R packages to work with `.h5mu` files.
For Seurat, there's [MuDataSeurat](https://github.com/PMBio/MuDataSeurat) now. There's also [MuData](https://github.com/PMBio/MuDataMAE) — a bioconductor-compatible package in case you're working with MultiAssayExperiment objects. 

`ReadH5MU` should now be properly exported and documented in these packages.

We hope the new packages will address the shortcoming of the experimental `muon.r` package.
Please feel free to get back with feedback in the respective repositories!

**Comment by gjhuizing** [comment]
Great, thanks for the quick reply!
